import { FileText } from "lucide-react";
import { LegalPage } from "@/components/legal-page";

export const metadata = {
  title: "Terms of Service · NexCart",
  description:
    "The rules of the road when you shop on NexCart — your rights, our responsibilities, and the fine print.",
};

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms of Service"
      Icon={FileText}
      title={
        <>
          The rules of the{" "}
          <span className="text-gradient-brand">road.</span>
        </>
      }
      intro="By creating an account on NexCart, browsing our store, or placing an order, you agree to these terms. We've written them in plain English so you can actually read them."
      updatedAt="14 May 2026"
      sections={[
        {
          id: "your-account",
          title: "Your account",
          body: (
            <>
              <p>
                You&apos;re responsible for keeping your sign-in details safe. If you suspect anyone else has access, change your password and email us immediately. You must be 16 or older to hold a NexCart account.
              </p>
              <p>
                We may suspend or terminate accounts that violate these terms, attempt fraud, abuse our staff, or scrape the catalog.
              </p>
            </>
          ),
        },
        {
          id: "orders-pricing",
          title: "Orders &amp; pricing",
          body: (
            <>
              <p>
                Prices, taxes, and shipping are shown at checkout in your local currency where available. Prices can change at any time, but once your order is confirmed, that price is locked in.
              </p>
              <p>
                If a product is mis-priced due to an obvious error (e.g. a $1,200 phone listed at $12), we may cancel and refund the order — we&apos;ll always tell you why.
              </p>
              <p>
                Acceptance happens when we send the shipping confirmation, not when you click &ldquo;Pay&rdquo;. Until then we can decline any order at our discretion.
              </p>
            </>
          ),
        },
        {
          id: "shipping-delivery",
          title: "Shipping &amp; delivery",
          body: (
            <p>
              We ship to 120+ countries. Standard delivery is free on orders over $50; otherwise a flat fee applies. Estimated transit times are shown at checkout and tracked in your account. We&apos;re not liable for delays caused by carriers, customs, or events outside our control.
            </p>
          ),
        },
        {
          id: "returns-warranty",
          title: "Returns &amp; warranty",
          body: (
            <>
              <p>
                We offer a <strong>7-day return window</strong> from the day your order is delivered, no questions asked, as long as items are in original condition and packaging. Refunds land within 5 business days of us receiving the return.
              </p>
              <p>
                Every product carries a <strong>2-year manufacturer warranty</strong> against defects in materials and workmanship. Wear and tear, drops, water damage, and unauthorised repairs are not covered.
              </p>
            </>
          ),
        },
        {
          id: "ai-features",
          title: "NexCart Intelligence (AI features)",
          body: (
            <p>
              NexCart Intelligence — including the in-store chatbot and AI-picked recommendations — is a tool to help you discover products. Outputs are generated by language models and may occasionally be inaccurate. Always confirm specs, prices, and policies on the product page or with our support team before acting on AI suggestions.
            </p>
          ),
        },
        {
          id: "acceptable-use",
          title: "Acceptable use",
          body: (
            <>
              <p>You agree not to:</p>
              <ul className="list-disc space-y-1.5 pl-5">
                <li>Reverse-engineer, scrape, or load-test our systems without written permission.</li>
                <li>Use NexCart for resale, dropshipping, or any commercial use without an agreement.</li>
                <li>Submit fraudulent payments, chargeback abuse, or fake reviews.</li>
                <li>Abuse our staff or other shoppers through any channel.</li>
              </ul>
            </>
          ),
        },
        {
          id: "ip",
          title: "Intellectual property",
          body: (
            <p>
              The NexCart name, logo, store design, code, and content are owned by NexCart Inc. Product images and brand names belong to their respective owners and are used with permission. You get a personal, non-transferable licence to use the store for shopping — nothing more.
            </p>
          ),
        },
        {
          id: "liability",
          title: "Limitation of liability",
          body: (
            <p>
              To the maximum extent permitted by law, NexCart&apos;s total liability for any claim arising out of these terms or your use of the store is limited to the amount you paid us in the 12 months before the claim arose. We&apos;re never liable for indirect, incidental, or consequential damages.
            </p>
          ),
        },
        {
          id: "governing-law",
          title: "Governing law",
          body: (
            <p>
              These terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-law rules. Disputes are resolved by binding arbitration in Wilmington, Delaware, unless your local consumer-protection laws require otherwise.
            </p>
          ),
        },
        {
          id: "changes",
          title: "Changes",
          body: (
            <p>
              We may update these terms occasionally. Material changes are emailed and announced on this page at least 14 days before they take effect.
            </p>
          ),
        },
      ]}
    />
  );
}
